// flow-typed signature: e051359db1bc2e9535cf75cc6a18ac68
// flow-typed version: <<STUB>>/@firebase/database_v^0.3.6/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/database'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/database' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@firebase/database/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@firebase/database/dist/index.esm' {
  declare module.exports: any;
}

declare module '@firebase/database/dist/index.node.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@firebase/database/dist/index.cjs.js' {
  declare module.exports: $Exports<'@firebase/database/dist/index.cjs'>;
}
declare module '@firebase/database/dist/index.esm.js' {
  declare module.exports: $Exports<'@firebase/database/dist/index.esm'>;
}
declare module '@firebase/database/dist/index.node.cjs.js' {
  declare module.exports: $Exports<'@firebase/database/dist/index.node.cjs'>;
}
